{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.torlando-tech.reticulum-kt",
    "module": "rns-interfaces",
    "version": "0.1.0-af9dc53f",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.github.torlando-tech.reticulum-kt",
          "module": "rns-core",
          "version": {
            "requires": "0.1.0-af9dc53f"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "rns-interfaces-0.1.0-af9dc53f.jar",
          "url": "rns-interfaces-0.1.0-af9dc53f.jar",
          "size": 485795,
          "sha512": "3941329147bff6f32de00762333f1c6462e130c017acfa1b5427fa70a9f4dd73e61ad91155b65c76257ae9928036b6e77c80a78ad895f9120e746c763b8b3784",
          "sha256": "f1d7bb1f015912cb0bd370be9a2109bfa97463f28a5d062ebe68a6212207925f",
          "sha1": "485588b986be6a16d7e34d54a68f3e79c38e0f82",
          "md5": "2c6d653db7ca6e461f4062eb7268de8b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.github.torlando-tech.reticulum-kt",
          "module": "rns-core",
          "version": {
            "requires": "0.1.0-af9dc53f"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "rns-interfaces-0.1.0-af9dc53f.jar",
          "url": "rns-interfaces-0.1.0-af9dc53f.jar",
          "size": 485795,
          "sha512": "3941329147bff6f32de00762333f1c6462e130c017acfa1b5427fa70a9f4dd73e61ad91155b65c76257ae9928036b6e77c80a78ad895f9120e746c763b8b3784",
          "sha256": "f1d7bb1f015912cb0bd370be9a2109bfa97463f28a5d062ebe68a6212207925f",
          "sha1": "485588b986be6a16d7e34d54a68f3e79c38e0f82",
          "md5": "2c6d653db7ca6e461f4062eb7268de8b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rns-interfaces-0.1.0-af9dc53f-sources.jar",
          "url": "rns-interfaces-0.1.0-af9dc53f-sources.jar",
          "size": 111881,
          "sha512": "f70092aabbc8a394142723393604f81216a6a2b99547d7975a3bc63c28aec3cff9b7e91e45f1acb853658df12e5dff993f9e6f967e19bc47d411b09ac746b92f",
          "sha256": "bb53776ce729d1746b63954fc257ffce31b53600851f4b1cf0cc017b232b5d7c",
          "sha1": "0d34a059239eb4a13ae0512d8d42344ebe64eade",
          "md5": "1845283a69fe421941693bdea1ccf802"
        }
      ]
    }
  ]
}
