{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.torlando-tech.reticulum-kt",
    "module": "rns-interfaces",
    "version": "0.1.0-1a7f6193",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.github.torlando-tech.reticulum-kt",
          "module": "rns-core",
          "version": {
            "requires": "0.1.0-1a7f6193"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "rns-interfaces-0.1.0-1a7f6193.jar",
          "url": "rns-interfaces-0.1.0-1a7f6193.jar",
          "size": 487220,
          "sha512": "d9ec503daac11158ea7856d301c830d67064f8b0fc0a1e2cf335a6000632c508941a7850df2b89b3b435952a6d69562cfdc7db0aecbe42d09b897383b251cdfe",
          "sha256": "7783065d5121b74ee3ee35dd6b899572a7acd08a4b6012989746567ffba70de4",
          "sha1": "468cee86e61450aa1cb2223013d24e7b1f2abaa0",
          "md5": "58dcc1418c138bebe72cf43c0ed97033"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.github.torlando-tech.reticulum-kt",
          "module": "rns-core",
          "version": {
            "requires": "0.1.0-1a7f6193"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "rns-interfaces-0.1.0-1a7f6193.jar",
          "url": "rns-interfaces-0.1.0-1a7f6193.jar",
          "size": 487220,
          "sha512": "d9ec503daac11158ea7856d301c830d67064f8b0fc0a1e2cf335a6000632c508941a7850df2b89b3b435952a6d69562cfdc7db0aecbe42d09b897383b251cdfe",
          "sha256": "7783065d5121b74ee3ee35dd6b899572a7acd08a4b6012989746567ffba70de4",
          "sha1": "468cee86e61450aa1cb2223013d24e7b1f2abaa0",
          "md5": "58dcc1418c138bebe72cf43c0ed97033"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rns-interfaces-0.1.0-1a7f6193-sources.jar",
          "url": "rns-interfaces-0.1.0-1a7f6193-sources.jar",
          "size": 113040,
          "sha512": "9f7a8ddc54ac0db0350c9a3892c475a0d7fc8d2662078135b5cd7a34492b1dedf5ccb4c8feb5d43ad65320c487e3198918fe3924f5899ba16e2ae040bef2e29a",
          "sha256": "112d1dc4cd6e62fc5267887e52b214491098a87965debf434c6b667ec5aef129",
          "sha1": "278cf2f00f1c664e40afdbfafc8fc175790b4d8a",
          "md5": "abc2bda9560e0154ed1348143088646c"
        }
      ]
    }
  ]
}
