{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.torlando-tech.reticulum-kt",
    "module": "rns-core",
    "version": "0.1.0-1a7f6193",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.msgpack",
          "module": "msgpack-core",
          "version": {
            "requires": "0.9.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "rns-core-0.1.0-1a7f6193.jar",
          "url": "rns-core-0.1.0-1a7f6193.jar",
          "size": 542190,
          "sha512": "9c04cd91c05e972d761552fba8a3c105c6e9a34af464f4f8130f0c093e1d46833534ba7820583045506e5ea590bac703d26e5cb44bbb1da07b619e333c87bb45",
          "sha256": "cbb3d2f1ce5bb88f04740ac308f4e2da4d67af25a748cdd60ed2af0a189e1feb",
          "sha1": "96e3f4ee073bc601b1dad5292a096268da9da9ed",
          "md5": "2652c506fbb3ed4aa2faba939143d439"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk18on",
          "version": {
            "requires": "1.77"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.26.0"
          }
        },
        {
          "group": "io.github.microutils",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "3.0.5"
          }
        },
        {
          "group": "org.msgpack",
          "module": "msgpack-core",
          "version": {
            "requires": "0.9.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "rns-core-0.1.0-1a7f6193.jar",
          "url": "rns-core-0.1.0-1a7f6193.jar",
          "size": 542190,
          "sha512": "9c04cd91c05e972d761552fba8a3c105c6e9a34af464f4f8130f0c093e1d46833534ba7820583045506e5ea590bac703d26e5cb44bbb1da07b619e333c87bb45",
          "sha256": "cbb3d2f1ce5bb88f04740ac308f4e2da4d67af25a748cdd60ed2af0a189e1feb",
          "sha1": "96e3f4ee073bc601b1dad5292a096268da9da9ed",
          "md5": "2652c506fbb3ed4aa2faba939143d439"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rns-core-0.1.0-1a7f6193-sources.jar",
          "url": "rns-core-0.1.0-1a7f6193-sources.jar",
          "size": 236197,
          "sha512": "d0386466991542344126ecbff59916e3eb20e35c20067df07f8e594d7fe7ddc78362e5e891a3fa6972fcc2bcc3f10c15ce6dacf2f4e6b4cd5ffa1f99a1537cf8",
          "sha256": "728b978eda764d5cc53a37df63f2c00c9689be6c71ebee52a66a8e2d1eda976c",
          "sha1": "224824eeafc02cc0b0b88ea300739ccd88dc7568",
          "md5": "d7a12a138a2ebd950e9facaf2abc9498"
        }
      ]
    }
  ]
}
