{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.torlando-tech.LXMF-kt",
    "module": "lxmf-core",
    "version": "0.1.0-74d343a0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.github.torlando-tech.reticulum-kt",
          "module": "rns-core",
          "version": {
            "requires": "0.1.0-af9dc53f"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "lxmf-core-0.1.0-74d343a0.jar",
          "url": "lxmf-core-0.1.0-74d343a0.jar",
          "size": 134137,
          "sha512": "e3493767006978e7761a0c480f83e5806b23a34500c0cc42a910437aaa0871129878907159ed5279b660702e6e4eaab0ff1c6c96034e7a4404ad2dd58156f82e",
          "sha256": "44d6a87e5175f72bea6449531c8ea797b8aefaca65d93785fe03e2d9c057deca",
          "sha1": "9fc69cd733a2dcd02c6102fc3dbd73cb4e639ea6",
          "md5": "3dfc518747c108ae5b9032bc43daa8b1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.msgpack",
          "module": "msgpack-core",
          "version": {
            "requires": "0.9.8"
          }
        },
        {
          "group": "io.github.microutils",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "3.0.5"
          }
        },
        {
          "group": "com.github.torlando-tech.reticulum-kt",
          "module": "rns-core",
          "version": {
            "requires": "0.1.0-af9dc53f"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "lxmf-core-0.1.0-74d343a0.jar",
          "url": "lxmf-core-0.1.0-74d343a0.jar",
          "size": 134137,
          "sha512": "e3493767006978e7761a0c480f83e5806b23a34500c0cc42a910437aaa0871129878907159ed5279b660702e6e4eaab0ff1c6c96034e7a4404ad2dd58156f82e",
          "sha256": "44d6a87e5175f72bea6449531c8ea797b8aefaca65d93785fe03e2d9c057deca",
          "sha1": "9fc69cd733a2dcd02c6102fc3dbd73cb4e639ea6",
          "md5": "3dfc518747c108ae5b9032bc43daa8b1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lxmf-core-0.1.0-74d343a0-sources.jar",
          "url": "lxmf-core-0.1.0-74d343a0-sources.jar",
          "size": 47903,
          "sha512": "c5b2aa05d5992a4410dcd549bbe7258852594e03fd2c8efde708450e9c8ea5877f00dc742a800658690121802f6c511f53f5e3ba781ccc7b80e465d4ee1021b4",
          "sha256": "84db833dcb42eb8199e1594f0548a8aab7ff939ed521b5ddb06d023e8f67005b",
          "sha1": "1e6b2e018e87b4703fcb6e7d70a9e62137ef90d4",
          "md5": "19ba74f6bc62aa1db774af5c54aa8a85"
        }
      ]
    }
  ]
}
