{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.torlando-tech.LXMF-kt",
    "module": "lxmf-core",
    "version": "0.1.0-74d343a0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.github.torlando-tech.reticulum-kt",
          "module": "rns-core",
          "version": {
            "requires": "0.1.0-1a7f6193"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "lxmf-core-0.1.0-74d343a0.jar",
          "url": "lxmf-core-0.1.0-74d343a0.jar",
          "size": 134137,
          "sha512": "cf645c9196662ee8daa75d0a69b9122672e3e6fd7c99355cdc65dcd6a6a2b099b778ea0039c48596a03e8722a71ae423bcb6f7d748ea4149d3caec7bf67243b0",
          "sha256": "2dc4ab48bfe6a3327432db320361c7bb43a0254dc3401db237132e953a3c400d",
          "sha1": "73332cd8bfd759d11a4588165dd1d37f8b0d4051",
          "md5": "2e7e0cc6e49656bb7a3628245b768062"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.msgpack",
          "module": "msgpack-core",
          "version": {
            "requires": "0.9.8"
          }
        },
        {
          "group": "io.github.microutils",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "3.0.5"
          }
        },
        {
          "group": "com.github.torlando-tech.reticulum-kt",
          "module": "rns-core",
          "version": {
            "requires": "0.1.0-1a7f6193"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "lxmf-core-0.1.0-74d343a0.jar",
          "url": "lxmf-core-0.1.0-74d343a0.jar",
          "size": 134137,
          "sha512": "cf645c9196662ee8daa75d0a69b9122672e3e6fd7c99355cdc65dcd6a6a2b099b778ea0039c48596a03e8722a71ae423bcb6f7d748ea4149d3caec7bf67243b0",
          "sha256": "2dc4ab48bfe6a3327432db320361c7bb43a0254dc3401db237132e953a3c400d",
          "sha1": "73332cd8bfd759d11a4588165dd1d37f8b0d4051",
          "md5": "2e7e0cc6e49656bb7a3628245b768062"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lxmf-core-0.1.0-74d343a0-sources.jar",
          "url": "lxmf-core-0.1.0-74d343a0-sources.jar",
          "size": 47903,
          "sha512": "43e8849dfbf7531bdf40616599dfc884b5d67ab5bd6cc0bd85832fbb890aa9b79169767458b5c04de7808928735364271a5a33cba4d9717cfb1eda1e654b15b6",
          "sha256": "175e7eb3f380993205feb81e4ae9cf3fd6556e1e493295efe0ab5ca4e7de898f",
          "sha1": "4ff4a2efd47d6a41bbf11e4a07eb33f7feeed2c8",
          "md5": "2c7d0fa24d303cbca873908e71311e6b"
        }
      ]
    }
  ]
}
