{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.torlando-tech.reticulum-kt",
    "module": "rns-interfaces",
    "version": "0.1.0-2a3d2c1e",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.github.torlando-tech.reticulum-kt",
          "module": "rns-core",
          "version": {
            "requires": "0.1.0-2a3d2c1e"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "rns-interfaces-0.1.0-2a3d2c1e.jar",
          "url": "rns-interfaces-0.1.0-2a3d2c1e.jar",
          "size": 485771,
          "sha512": "3b4a5cbc7079526f2142fe2214b251d8420c320c617e29a04fe7a6ac3fb0df9034b59be20169259a6e53433a6a6f502ba7746add06d824641c64408c0c94340b",
          "sha256": "04a064aab91d864b9f386e1e37e6cc1fc684e6a7fce7d4fe3ec32c85114ece18",
          "sha1": "674b398bdad9a91ce9e5404191e15159b600ad2f",
          "md5": "5aa2ac164a33c480b2de8cc333110086"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.github.torlando-tech.reticulum-kt",
          "module": "rns-core",
          "version": {
            "requires": "0.1.0-2a3d2c1e"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "rns-interfaces-0.1.0-2a3d2c1e.jar",
          "url": "rns-interfaces-0.1.0-2a3d2c1e.jar",
          "size": 485771,
          "sha512": "3b4a5cbc7079526f2142fe2214b251d8420c320c617e29a04fe7a6ac3fb0df9034b59be20169259a6e53433a6a6f502ba7746add06d824641c64408c0c94340b",
          "sha256": "04a064aab91d864b9f386e1e37e6cc1fc684e6a7fce7d4fe3ec32c85114ece18",
          "sha1": "674b398bdad9a91ce9e5404191e15159b600ad2f",
          "md5": "5aa2ac164a33c480b2de8cc333110086"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "rns-interfaces-0.1.0-2a3d2c1e-sources.jar",
          "url": "rns-interfaces-0.1.0-2a3d2c1e-sources.jar",
          "size": 111640,
          "sha512": "3571cad3bb0cde0c7c1b7804d3468cd316c0d68312e9cfe1bd65f953cceae08adc49ddd8a6da66288ef2cb460233f93f49427ec041384f91538c90fa6ae2e134",
          "sha256": "b880c5b93ff80dd9e62a036e1959cd49ee4f1b38fbf6dc6469b11b436c9995bc",
          "sha1": "0a0c1b132654ef454c0fc64e4b9a4a6139bef313",
          "md5": "646fa1aacf03228359102eff49fa13be"
        }
      ]
    }
  ]
}
